Update clamscanrunner
多重起動防止のpgerp結果がbashになってしまうのでロックファイル形式に戻した。
exitの際、ロックファイルを削除するようにした。

diff --git a/clamscanrunner b/clamscanrunner
--- a/clamscanrunner
+++ b/clamscanrunner
@@ -14,6 +14,12 @@ usage_exit() {
         exit 1
 }
 
+delete_lock_and_exit() {
+        echo "${2}_${4}" >>"${3}"
+        rm "${1}"
+        exit "${4}"
+}
+
 ENABLE_f="f"
 
 
@@ -59,13 +65,12 @@ fi
 
 #多重起動防止機講
 # 制限が有効で、同じ名前のプロセスが起動していたら起動しない。
-if [ "${ENABLE_f}" != "t" ]; then  
-CMDLINE=$(cat /proc/$$/cmdline | xargs --null)
-if [[ $$ -ne $(pgrep -oxf "${CMDLINE}") ]]; then
-echo 'Cannot run multiple instance.' >> ${LOGFILE} 2>&1
-exit 9
+_lockfile="/tmp/`basename $0`.lock"
+if [ "${ENABLE_f}" = "t" ]; then  
+rm -f $_lockfile
 fi
-fi
+ln -s /dummy $_lockfile 2> /dev/null || { echo 'Cannot run multiple instance.'  >>"${LOGFILE}"; exit 9; }
+trap "rm $_lockfile; exit" 1 2 3 15
 
 # ファイル更新日時が5000日を越えたログファイルを削除
 readonly PARAM_DATE_NUM=5000
@@ -94,7 +99,7 @@ STATUS_CLAMONACC_PRE_BEFORE_SCAN=$(systemctl is-active clamonacc)
 echo "clamonaccの状態(停止前) = ${STATUS_CLAMONACC_PRE_BEFORE_SCAN}" >> ${LOGFILE} 2>&1
 if [ "${STATUS_CLAMONACC_PRE_BEFORE_SCAN}" = "${STATUS_ACTIVE}" ]; then
 echo "clamonaccの停止" >> ${LOGFILE} 2>&1
-systemctl stop clamonacc >> ${LOGFILE} 2>&1 || exit 4
+systemctl stop clamonacc >> ${LOGFILE} 2>&1 || delete_lock_and_exit $_lockfile "clamonaccの停止に失敗しました。終了します。" ${LOGFILE} 4
 STATUS_CLAMONACC_POST_BEFORE_SCAN=$(systemctl is-active clamonacc)
 echo "clamonaccの状態(停止後) = ${STATUS_CLAMONACC_POST_BEFORE_SCAN}" >> ${LOGFILE} 2>&1
 fi
@@ -103,7 +108,7 @@ STATUS_CLAMD_PRE_BEFORE_SCAN=$(systemctl is-active clamd@scan)
 echo "clamdの状態(停止前) = ${STATUS_CLAMD_PRE_BEFORE_SCAN}" >> ${LOGFILE} 2>&1
 if [ "${STATUS_CLAMD_PRE_BEFORE_SCAN}" = "${STATUS_ACTIVE}" ]; then
 echo "clamdの停止" >> ${LOGFILE} 2>&1
-systemctl stop clamd@scan >> ${LOGFILE} 2>&1 || exit 5
+systemctl stop clamd@scan >> ${LOGFILE} 2>&1 || delete_lock_and_exit $_lockfile "clamdの停止に失敗しました。終了します。" ${LOGFILE} 5
 STATUS_CLAMD_POST_BEFORE_SCAN=$(systemctl is-active clamd@scan)
 echo "clamdの状態(停止後) = ${STATUS_CLAMD_POST_BEFORE_SCAN}" >> ${LOGFILE} 2>&1
 fi
@@ -114,33 +119,33 @@ echo "オンアクセススキャンの停止を完了。\n" >> ${LOGFILE} 2>&1
 # virus scan
 #感染したファイルのみログに記載する。
 #感染したファイルは削除する。
-clamscan / -r --infected --remove --exclude-dir='/sys|/proc|/dev' >> ${LOGFILE} 2>&1 || exit 6
+clamscan / -r --infected --remove --exclude-dir='/sys|/proc|/dev' >> ${LOGFILE} 2>&1 || delete_lock_and_exit $_lockfile "clamscanに失敗しました。終了します。" ${LOGFILE} 6
 
 
 echo "\nオンアクセススキャンを再開する。" >> ${LOGFILE} 2>&1
-
-STATUS_CLAMONACC_PRE_AFTER_SCAN=$(systemctl is-active clamonacc)
-echo "clamonaccの状態(再開前) = ${STATUS_CLAMONACC_PRE_AFTER_SCAN}" >> ${LOGFILE} 2>&1
-if [ "${STATUS_CLAMONACC_PRE_AFTER_SCAN}" = "${STATUS_ACTIVE}" ]; then
-echo "clamonaccの開始" >> ${LOGFILE} 2>&1
-systemctl start clamonacc >> ${LOGFILE} 2>&1 || exit 7
-STATUS_CLAMONACC_POST_AFTER_SCAN=$(systemctl is-active clamonacc)
-echo "clamonaccの状態(再開後) = ${STATUS_CLAMONACC_POST_AFTER_SCAN}" >> ${LOGFILE} 2>&1
-fi
 
 STATUS_CLAMD_PRE_AFTER_SCAN=$(systemctl is-active clamd@scan)
 echo "clamdの状態(再開前前) = ${STATUS_CLAMD_PRE_AFTER_SCAN}" >> ${LOGFILE} 2>&1
 if [ "${STATUS_CLAMD_PRE_AFTER_SCAN}" = "${STATUS_ACTIVE}" ]; then
 echo "clamdの開始" >> ${LOGFILE} 2>&1
-systemctl start clamd@scan >> ${LOGFILE} 2>&1 || exit 8
+systemctl start clamd@scan >> ${LOGFILE} 2>&1 ||  delete_lock_and_exit $_lockfile "clamdの開始に失敗しました。終了します。" ${LOGFILE} 7
 STATUS_CLAMD_POST_AFTER_SCAN=$(systemctl is-active clamd@scan)
 echo "clamdの状態(再開後) = ${STATUS_CLAMD_POST_AFTER_SCAN}" >> ${LOGFILE} 2>&1
+fi
+
+STATUS_CLAMONACC_PRE_AFTER_SCAN=$(systemctl is-active clamonacc)
+echo "clamonaccの状態(再開前) = ${STATUS_CLAMONACC_PRE_AFTER_SCAN}" >> ${LOGFILE} 2>&1
+if [ "${STATUS_CLAMONACC_PRE_AFTER_SCAN}" = "${STATUS_ACTIVE}" ]; then
+echo "clamonaccの開始" >> ${LOGFILE} 2>&1
+systemctl start clamonacc >> ${LOGFILE} 2>&1 || delete_lock_and_exit $_lockfile "clamonaccの開始に失敗しました。終了します。" ${LOGFILE} 8
+STATUS_CLAMONACC_POST_AFTER_SCAN=$(systemctl is-active clamonacc)
+echo "clamonaccの状態(再開後) = ${STATUS_CLAMONACC_POST_AFTER_SCAN}" >> ${LOGFILE} 2>&1
 fi
 
 echo "オンアクセススキャンの再開を完了。\n" >> ${LOGFILE} 2>&1
 
 
-
 #ログファイルの内容を表示
 cat ${LOGFILE}
 
+rm $_lockfile
