フォーマット整形

diff --git a/remove_clamscan_runner_lockfile b/remove_clamscan_runner_lockfile
--- a/remove_clamscan_runner_lockfile
+++ b/remove_clamscan_runner_lockfile
@@ -2,14 +2,13 @@
 PROCNAME="${1}"
 
 if [ -z "${PROCNAME}" ]; then
- echo "String Error."
- exit 1
+	echo "String Error."
+	exit 1
 fi
 
 LOCKFILE="/tmp/${PROCNAME}.lock"
-ps=`ps aux | grep ${PROCNAME} | grep -v grep | grep -v "${BASH_SOURCE[0]##*/}" | wc -l`
-  if [ $ps -eq 0 ]; then # 対象プロセスが存在しない場合
-    rm -f "${LOCKFILE}"
-    exit 0
-  fi
-
+ps=$(ps aux | grep ${PROCNAME} | grep -v grep | grep -v "${BASH_SOURCE[0]##*/}" | wc -l)
+if [ $ps -eq 0 ]; then # 対象プロセスが存在しない場合
+	rm -f "${LOCKFILE}"
+	exit 0
+fi
